language: scala

sudo: required
dist: trusty
services: docker

addons:
  apt:
    packages:
      - shellcheck

env:
  matrix:
    - RELEASE=false

before_install:
  - git fetch --tags
  - docker pull exasol/docker-db:latest
  - docker pull exasol/docker-db:6.2.7-d1

matrix:
  include:
    - jdk: openjdk11
      scala: 2.12.12

    - jdk: oraclejdk11
      scala: 2.12.12
      env: RELEASE=true

script:
  - travis_wait 30 ./scripts/ci.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./sbtx coveralls

before_deploy:
  - echo "Ensure assembly jar file is created for a $TRAVIS_TAG"
  - ./sbtx clean assembly
  - export JAR_VERSION=${TRAVIS_TAG}
  - echo "Jar artifact version $JAR_VERSION"
  - mkdir -p artifacts
  - cp target/scala-2.12/exasol-kinesis-connector-extension-${JAR_VERSION}.jar artifacts/
  - echo "Create SHA256 Checksum"
  - cd artifacts
  - sha256sum exasol-kinesis-connector-extension-${JAR_VERSION}.jar > checksum.sha256.txt
  - cd ../
  - ls -lh artifacts/

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - artifacts/exasol-kinesis-connector-extension-${JAR_VERSION}.jar
    - artifacts/checksum.sha256.txt
  skip_cleanup: true
  on:
    repo: exasol/kinesis-connector-extension
    tags: true
    condition: $RELEASE = true && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$

cache:
  directories:
    - "$HOME/.sbt/1.0"
    - "$HOME/.sbt/boot/scala*"
    - "$HOME/.sbt/cache"
    - "$HOME/.sbt/launchers"
    - "$HOME/.ivy2"
    - "$HOME/.coursier"

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete